{
  "id": "oval:org.opensuse.security:def:20140481",
  "version": "1",
  "class": "vulnerability",
  "metadata": {
    "Title": "CVE-2014-0481",
    "affected": {
      "family": "unix",
      "Platform": [
        "openSUSE 13.1"
      ]
    },
    "reference": [
      {
        "ref_id": "CVE-2014-0481",
        "ref_url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0481",
        "source": "CVE"
      }
    ],
    "Description": "\n    The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.\n    ",
    "advisory": {
      "Severity": "",
      "cve": {},
      "issued": {},
      "updated": {},
      "affected_cpe_list": {
        "Cpe": null
      }
    }
  },
  "criteria": {
    "operator": "AND",
    "criterions": [
      {
        "test_ref": "oval:org.opensuse.security:tst:2009117513",
        "comment": "openSUSE 13.1 is installed"
      },
      {
        "test_ref": "oval:org.opensuse.security:tst:2009100526",
        "comment": "python-django-1.5.10-0.2.8.1 is installed"
      }
    ]
  }
}
