{
	"id": "oval:org.opensuse.security:def:202326303",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2023-26303",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Leap 15.5"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2023-26303",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-26303",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2023-26303",
				"ref_url": "https://www.suse.com/security/cve/CVE-2023-26303",
				"source": "SUSE CVE"
			}
		],
		"description": "\n    Denial of service could be caused to markdown-it-py, before v2.2.0, if an attacker was allowed to force null assertions with specially crafted input.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Low",
			"cve": [
				{
					"text": "CVE-2023-26303 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2023-26303/",
					"impact": "low",
					"cvss3": "3.3/CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
				},
				{
					"text": "CVE-2023-26303 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2023-26303",
					"impact": "low",
					"cvss3": "3.3/CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1208974",
					"href": "https://bugzilla.suse.com/1208974"
				}
			],
			"issued": {
				"date": "2024-06-12"
			},
			"updated": {
				"date": "2024-06-12"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:leap:15.5"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009752682",
				"comment": "openSUSE Leap 15.5 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009865394",
				"comment": "python-markdown-it-py is not affected"
			}
		]
	}
}
