{
	"id": "oval:org.opensuse.security:def:20064980",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2006-4980",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Desktop 12 SP4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2006-4980",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2006-4980",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2006-4980",
				"ref_url": "https://www.suse.com/security/cve/CVE-2006-4980",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SR:2006:025",
				"ref_url": "https://lists.opensuse.org/opensuse-security-announce/2006-10/msg00013.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    Buffer overflow in the repr function in Python 2.3 through 2.6 before 20060822 allows context-dependent attackers to cause a denial of service and possibly execute arbitrary code via crafted wide character UTF-32/UCS-4 strings to certain scripts.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2006-4980",
					"href": "https://www.suse.com/security/cve/CVE-2006-4980/",
					"impact": "important"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 208223",
					"href": "https://bugzilla.suse.com/208223"
				},
				{
					"text": "SUSE bug 406051",
					"href": "https://bugzilla.suse.com/406051"
				}
			],
			"issued": {
				"date": "2022-05-20"
			},
			"updated": {
				"date": "2022-05-20"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:suse:sled:12:sp4"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009239879",
				"comment": "SUSE Linux Enterprise Desktop 12 SP4 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009334122",
				"comment": "python is not affected"
			}
		]
	}
}
