{
	"id": "oval:org.opensuse.security:def:20082316",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2008-2316",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Desktop 12 SP4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2008-2316",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-2316",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2008-2316",
				"ref_url": "https://www.suse.com/security/cve/CVE-2008-2316",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SR:2008:017",
				"ref_url": "https://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2020:0234-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-January/006406.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    Integer overflow in _hashopenssl.c in the hashlib module in Python 2.5.2 and earlier might allow context-dependent attackers to defeat cryptographic digests, related to \"partial hashlib hashing of data exceeding 4GB.\"\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2008-2316",
					"href": "https://www.suse.com/security/cve/CVE-2008-2316/",
					"impact": "important"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 406051",
					"href": "https://bugzilla.suse.com/406051"
				}
			],
			"issued": {
				"date": "2022-05-20"
			},
			"updated": {
				"date": "2022-05-20"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:suse:sled:12:sp4"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009239879",
				"comment": "SUSE Linux Enterprise Desktop 12 SP4 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009334164",
				"comment": "python is affected"
			}
		]
	}
}
