{
	"id": "oval:org.opensuse.security:def:20081887",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2008-1887",
		"affected": {
			"family": "unix",
			"Platform": [
				"SUSE Linux Enterprise Desktop 12 SP4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2008-1887",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2008-1887",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2008-1887",
				"ref_url": "https://www.suse.com/security/cve/CVE-2008-1887",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SR:2008:017",
				"ref_url": "https://lists.opensuse.org/opensuse-security-announce/2008-08/msg00006.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    Python 2.5.2 and earlier allows context-dependent attackers to execute arbitrary code via multiple vectors that cause a negative size value to be provided to the PyString_FromStringAndSize function, which allocates less memory than expected when assert() is disabled and triggers a buffer overflow.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Critical",
			"cve": {
				"text": "CVE-2008-1887",
				"href": "https://www.suse.com/security/cve/CVE-2008-1887/",
				"impact": "critical"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 379534",
					"href": "https://bugzilla.suse.com/379534"
				}
			],
			"issued": {
				"date": "2021-11-24"
			},
			"updated": {
				"date": "2021-11-24"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:suse:sled:12:sp4"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009239879",
				"comment": "SUSE Linux Enterprise Desktop 12 SP4 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009334122",
				"comment": "python is not affected"
			}
		]
	}
}
