{
	"id": "oval:org.opensuse.security:def:202133430",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2021-33430",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Leap 15.4"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2021-33430",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-33430",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2021-33430",
				"ref_url": "https://www.suse.com/security/cve/CVE-2021-33430",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-CU-2022:314-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-March/010482.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-CU-2022:315-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-March/010483.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-CU-2022:316-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-March/010484.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:0118-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010024.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:0134-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010033.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:0134-2",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-February/010254.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:0134-3",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-October/012546.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:0206-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-January/010122.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:1064-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-March/010612.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:1064-2",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-September/012215.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2022:2441-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2022-July/011595.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "openSUSE-SU-2022:0134-1",
				"ref_url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/LQS3J3J4254A7C3LD55D7A432FZ2RFFI/",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "openSUSE-SU-2022:1064-1",
				"ref_url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/IVU5XH7TX2TXVVZCKS7DIEBNEJKYZTSK/",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    ** DISPUTED ** A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2021-33430",
					"href": "https://www.suse.com/security/cve/CVE-2021-33430/",
					"impact": "important",
					"cvss3": "7.5/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1193913",
					"href": "https://bugzilla.suse.com/1193913"
				},
				{
					"text": "SUSE bug 1201968",
					"href": "https://bugzilla.suse.com/1201968"
				}
			],
			"issued": {
				"date": "2022-06-30"
			},
			"updated": {
				"date": "2022-10-18"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:leap:15.4"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "AND",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009686252",
						"comment": "python3-numpy-1.17.3-150400.21.32 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009245328",
						"comment": "python3-numpy is signed with openSUSE key"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009697593",
				"comment": "openSUSE Leap 15.4 is installed"
			}
		]
	}
}
