{
	"id": "oval:org.opensuse.security:def:20198341",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2019-8341",
		"affected": {
			"family": "unix",
			"platform": [
				"SUSE Linux Enterprise Server 11 SP3"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2019-8341",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-8341",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2019-8341",
				"ref_url": "https://www.suse.com/security/cve/CVE-2019-8341",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-CU-2020:209-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-June/006960.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-CU-2020:215-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-June/006962.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-CU-2020:218-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-June/006963.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-CU-2020:221-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-June/006964.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-IU-2021:6-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2021-February/008294.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-IU-2021:605-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2021-August/009236.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2019:1156-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2019-May/005424.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2019:1554-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2019-June/005583.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2020:3096-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-October/007672.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2020:3896-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-December/008098.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2020:3897-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2020-December/008099.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "openSUSE-SU-2019:1395-1",
				"ref_url": "https://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "openSUSE-SU-2019:1614-1",
				"ref_url": "https://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "unknown",
				"ref_url": "https://lists.suse.com/archive/suse-security-announce/2007-Jun/0001.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    ** DISPUTED ** An issue was discovered in Jinja2 2.10. The from_string function is prone to Server Side Template Injection (SSTI) where it takes the \"source\" parameter as a template object, renders it, and then returns it. The attacker can exploit it with {{INJECTION COMMANDS}} in a URI. NOTE: The maintainer and multiple third parties believe that this vulnerability isn't valid because users shouldn't use untrusted templates without sandboxing.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Important",
			"cve": [
				{
					"text": "CVE-2019-8341",
					"href": "https://www.suse.com/security/cve/CVE-2019-8341/",
					"impact": "important",
					"cvss3": "8.2/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1125815",
					"href": "https://bugzilla.suse.com/1125815"
				}
			],
			"issued": {
				"date": "2022-05-20"
			},
			"updated": {
				"date": "2022-05-20"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:suse:suse_sles:11:sp3"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009077550",
				"comment": "SUSE Linux Enterprise Server 11 SP3 is installed"
			},
			{
				"test_ref": "oval:org.opensuse.security:tst:2009334679",
				"comment": "python-Jinja2 is affected"
			}
		]
	}
}
