{
	"id": "oval:org.opensuse.security:def:20132132",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2013-2132",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2013-2132",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-2132",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2013-2132",
				"ref_url": "https://www.suse.com/security/cve/CVE-2013-2132",
				"source": "SUSE CVE"
			}
		],
		"description": "\n    bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\"\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2013-2132 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2013-2132/"
				},
				{
					"text": "CVE-2013-2132 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2013-2132"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 822798",
					"href": "https://bugzilla.suse.com/822798"
				}
			],
			"issued": {
				"date": "2021-10-02"
			},
			"updated": {
				"date": "2024-09-01"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009906911",
						"comment": "python-pymongo-3.1.1-1.5 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009906912",
						"comment": "python3-pymongo-3.4.0-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937997",
						"comment": "python310-pymongo-4.6.3-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937998",
						"comment": "python311-pymongo-4.6.3-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009937999",
						"comment": "python312-pymongo-4.6.3-1.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912740",
						"comment": "python36-pymongo-3.11.4-1.2 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912741",
						"comment": "python38-pymongo-3.11.4-1.2 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009912742",
						"comment": "python39-pymongo-3.11.4-1.2 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
