{
	"id": "oval:org.opensuse.security:def:202248565",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"Title": "CVE-2022-48565",
		"affected": {
			"family": "unix",
			"Platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2022-48565",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-48565",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2022-48565",
				"ref_url": "https://www.suse.com/security/cve/CVE-2022-48565",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2023:4001-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016561.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2023:4220-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016861.html",
				"source": "SUSE-SU"
			}
		],
		"Description": "\n    An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"Severity": "Moderate",
			"cve": {
				"text": "CVE-2022-48565",
				"href": "https://www.suse.com/security/cve/CVE-2022-48565/",
				"impact": "moderate",
				"cvss3": "5.3/CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L"
			},
			"bugzilla": [
				{
					"text": "SUSE bug 1214685",
					"href": "https://bugzilla.suse.com/1214685"
				},
				{
					"text": "SUSE bug 1221186",
					"href": "https://bugzilla.suse.com/1221186"
				}
			],
			"issued": {
				"date": "2023-09-23"
			},
			"updated": {
				"date": "2024-03-13"
			},
			"affected_cpe_list": {
				"Cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798614",
						"comment": "python-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798615",
						"comment": "python-32bit-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798616",
						"comment": "python-curses-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798617",
						"comment": "python-demo-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798618",
						"comment": "python-gdbm-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798619",
						"comment": "python-idle-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798620",
						"comment": "python-tk-2.7.18-39.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
