{
	"id": "oval:org.opensuse.security:def:202248565",
	"version": "1",
	"class": "vulnerability",
	"metadata": {
		"title": "CVE-2022-48565",
		"affected": {
			"family": "unix",
			"platform": [
				"openSUSE Tumbleweed"
			]
		},
		"reference": [
			{
				"ref_id": "Mitre CVE-2022-48565",
				"ref_url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-48565",
				"source": "CVE"
			},
			{
				"ref_id": "SUSE CVE-2022-48565",
				"ref_url": "https://www.suse.com/security/cve/CVE-2022-48565",
				"source": "SUSE CVE"
			},
			{
				"ref_id": "SUSE-SU-2023:4001-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016561.html",
				"source": "SUSE-SU"
			},
			{
				"ref_id": "SUSE-SU-2023:4220-1",
				"ref_url": "https://lists.suse.com/pipermail/sle-security-updates/2023-October/016861.html",
				"source": "SUSE-SU"
			}
		],
		"description": "\n    An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.\n    ",
		"advisory": {
			"from": "security@suse.de",
			"severity": "Moderate",
			"cve": [
				{
					"text": "CVE-2022-48565 at SUSE",
					"href": "https://www.suse.com/security/cve/CVE-2022-48565/",
					"impact": "medium",
					"cvss3": "5.3/CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:L/A:L"
				},
				{
					"text": "CVE-2022-48565 at NVD",
					"href": "https://nvd.nist.gov/vuln/detail/CVE-2022-48565",
					"impact": "critical",
					"cvss3": "9.8/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			],
			"bugzilla": [
				{
					"text": "SUSE bug 1214685",
					"href": "https://bugzilla.suse.com/1214685"
				},
				{
					"text": "SUSE bug 1221186",
					"href": "https://bugzilla.suse.com/1221186"
				}
			],
			"issued": {
				"date": "2023-09-23"
			},
			"updated": {
				"date": "2024-04-26"
			},
			"affected_cpe_list": {
				"cpe": [
					"cpe:/o:opensuse:tumbleweed"
				]
			}
		}
	},
	"criteria": {
		"operator": "AND",
		"criterias": [
			{
				"operator": "OR",
				"criterions": [
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798614",
						"comment": "python-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798615",
						"comment": "python-32bit-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798616",
						"comment": "python-curses-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798617",
						"comment": "python-demo-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798618",
						"comment": "python-gdbm-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798619",
						"comment": "python-idle-2.7.18-39.1 is installed"
					},
					{
						"test_ref": "oval:org.opensuse.security:tst:2009798620",
						"comment": "python-tk-2.7.18-39.1 is installed"
					}
				]
			}
		],
		"criterions": [
			{
				"test_ref": "oval:org.opensuse.security:tst:2009634834",
				"comment": "openSUSE Tumbleweed is installed"
			}
		]
	}
}
